# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [4]:
# ejercicio 1
a = np.array([1,2,3,4])
np.all(a == 0)

np.False_

In [5]:
# ejercicio 2
a = np.array([0,0,2,0])
np.any(a != 0)

np.True_

In [ ]:
# ejercicio  3
a = np.array([1,2,np.nan,np.inf])
np.isinf(a), np.isnan(a)

(array([False, False, False,  True]), array([False, False,  True, False]))

In [7]:
# ejercicio 4
a = np.array([1,2,np.inf])
np.isinf(a).any()

np.True_

In [8]:
# ejercicio 5
a = np.array([1,np.nan,3])
np.isnan(a).any()

np.True_

In [9]:
# ejercicio 6
a = np.array([1,3,5])
b = np.array([2,3,4])
a>b, a>=b, a<b, a<=b

(array([False, False,  True]),
 array([False,  True,  True]),
 array([ True, False, False]),
 array([ True,  True, False]))

In [10]:
# ejercicio 7
arr = np.array([1,7,13,105])
arr.nbytes

32

In [11]:
# ejercicio 8
np.zeros(10), np.ones(10), np.full(10,5)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]))

In [12]:
# ejercicio 9
np.arange(30,71)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [13]:
# ejercicio 10
np.arange(30,71,2)

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [15]:
# ejercicio 11
import random

def generar_matriz_aleatoria(N):
    matriz = []
    for i in range(N):
        fila = []
        for j in range(N):
            fila.append(random.randint(1, 9))
        matriz.append(fila)
    return matriz

def imprimir_matriz(matriz):
    for fila in matriz:
        fila_formateada = ' '.join(f'{elemento:2}' for elemento in fila)
        print(fila_formateada)

# Generar matriz 3x3
print("Matriz de 3x3:")
m_3 = generar_matriz_aleatoria(3)
imprimir_matriz(m_3)


Matriz de 3x3:
 1  9  1
 9  3  5
 5  5  3


In [16]:
# ejercicio 12
np.random.rand()

0.20296872980862513

In [17]:
# ejercicio 13
np.random.randn(15)

array([-1.21450714,  0.90117017,  0.06851381,  0.03410999, -0.26404312,
       -0.86207118,  0.34402382, -0.38378162,  0.70191575, -0.52512877,
        0.36124899,  1.18162511,  1.38935282, -1.01991088,  1.06891749])

In [18]:
# ejercicio 14
arr = np.arange(15,56)
arr[1:-1]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [19]:
# ejercicio 15
np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [20]:
# ejercicio 16
v = np.arange(21)
v[9:16] *= -1
v

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19,  20])

In [21]:
# ejercicio 17
a = np.array([1,2,3]).tolist()

In [22]:
# ejercicio 18
l = [1,2,3]
np.array(l)

array([1, 2, 3])

In [23]:
# ejercicio 19
m = np.array([[1,2],[3,4]])
m % 2 == 0

array([[False,  True],
       [False,  True]])

In [24]:
# ejercicio 20
m = np.array([[1,2,3],[4,5,6]])
filas = np.size(m, 0)
columnas = np.size(m, 1)
